<a href="https://colab.research.google.com/github/niikun/DL_for_health_care/blob/main/np_recarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# recarray

numpy.recarrayは、NumPyライブラリの一部であり、構造化配列（structured array）の一種です。  
recarrayは「レコード配列」の略であり、フィールド名を使用して配列の各フィールドにアクセスできる点が特徴です。   
通常のNumPy配列とは異なり、各要素が異なるデータ型を持つことができます。  
これにより、表形式のデータをより柔軟に扱うことができます。  
※通常のNumPyの配列（numpy.array）は、同じデータ型の要素を効率的に処理するために設計されています。これは数値計算や大量のデータを扱う場合に非常に便利です。しかし、この制限により、異なるデータ型を含むデータを同じ配列で扱うことはできません。

例えば、学校のクラスの生徒の名前、年齢、身長をまとめて管理することができます。普通のリストや配列（アレイ）と違って、recarrayは違う種類のデータを一緒にまとめることができるのが特徴です。
## 簡単な例  
クラスにAlice,Bob,Charlieという生徒がいるとします。それぞれの名前、年齢、体重を管理したいとき、recarrayを使うと次のようにできます。




### Step1.インポート

In [1]:
import numpy as np

###Step.2 データの作成

In [3]:
data = [
    ('Alice', 10, 30.5),
    ('Bob', 12, 35.3),
    ('Charlie', 11, 32.1)
]

### Step3. データの種類を決める  
それぞれのデータが何の種類か（名前は文字、年齢は数字、体重も数字）を決めます。  
- nameフィールド:   
'U10'は、長さ10までのUnicode文字列を表します。名前を文字列として保存します。
- ageフィールド:   
'i4'は、4バイトの整数を表します。年齢を整数として保存します。
- weightフィールド:   
'f4'は、4バイトの浮動小数点数を表します。体重を小数点付きの数値として保存します。

In [4]:
# データの種類を定義
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

###Step4.recarrayを作る  
recarrayを作って、データを入れます。

In [8]:
array = np.array(data,dtype=dtype)
array

array([('Alice', 10, 30.5), ('Bob', 12, 35.3), ('Charlie', 11, 32.1)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [10]:
# recarrayの作成
rec_array = np.array(data, dtype=dtype).view(np.recarray)
rec_array

rec.array([('Alice', 10, 30.5), ('Bob', 12, 35.3), ('Charlie', 11, 32.1)],
          dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

### Step5.データを使ってみる  
作ったrecarrayからデータを取り出して使います。

In [15]:
# 名前、年齢、体重を表示
print(f"Names: {rec_array.name}")   # 名前: ['Alice' 'Bob' 'Charlie']
print(f"Ages: {rec_array.age}")     # 年齢: [10 12 11]
print(f"Weights: {rec_array.weight}") # 体重: [30.5 35.3 32.1]

# 例えば、年齢が12歳以上の人の名前を知りたいとき
older_than_11 = rec_array[rec_array.age > 11]
print(f"Older than 11: {older_than_11.name}")  # 12歳以上: ['Bob']


Names: ['Alice' 'Bob' 'Charlie']
Ages: [10 12 11]
Weights: [30.5 35.3 32.1]
Older than 11: ['Bob']


## 構造化配列の例
構造化配列を使うと、異なるデータ型を同じ配列に含めることができます。

In [16]:
import numpy as np

# データとデータ型の定義
data = [
    ('Alice', 10, 30.5),
    ('Bob', 12, 35.3),
    ('Charlie', 11, 32.1)
]
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

# 構造化配列の作成
structured_array = np.array(data, dtype=dtype)

# フィールドへのアクセス
print(structured_array['name'])   # ['Alice' 'Bob' 'Charlie']
print(structured_array['age'])    # [10 12 11]
print(structured_array['weight']) # [30.5 35.3 32.1]


['Alice' 'Bob' 'Charlie']
[10 12 11]
[30.5 35.3 32.1]


### 構造化配列（structured array）とレコード配列（recarray）の違い
どちらもNumPyで異なるデータ型を持つデータを扱うための手法です。主な違いは、アクセス方法と機能にあります。

#### 構造化配列（structured array）
構造化配列は、異なるデータ型を持つ複数のフィールドを持つ配列です。フィールド名でデータにアクセスすることができますが、通常のNumPy配列と同様の方法で操作されます。

- 特徴
  - フィールド名でアクセス: 各フィールドにフィールド名を使ってアクセスできます。
  - 通常のNumPy配列と同じ操作: 通常のNumPy配列と同じようにスライスやブールインデックスを使った操作が可能です。

In [17]:
import numpy as np

# データとデータ型の定義
data = [
    ('Alice', 10, 30.5),
    ('Bob', 12, 35.3),
    ('Charlie', 11, 32.1)
]
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

# 構造化配列の作成
structured_array = np.array(data, dtype=dtype)

# フィールドへのアクセス
print(structured_array['name'])   # ['Alice' 'Bob' 'Charlie']
print(structured_array['age'])    # [10 12 11]
print(structured_array['weight']) # [30.5 35.3 32.1]


['Alice' 'Bob' 'Charlie']
[10 12 11]
[30.5 35.3 32.1]


### レコード配列（recarray）
レコード配列は構造化配列の特別な形式で、フィールド名に加えて属性（属性アクセス）としてもフィールドにアクセスできるようにするものです。これにより、コードの可読性が向上します。

- 特徴
  - フィールド名でのアクセス: 構造化配列と同様にフィールド名でアクセスできます。
  - 属性アクセス: フィールド名を属性として使ってアクセスできます（ドット表記）。

In [18]:
import numpy as np

# データとデータ型の定義
data = [
    ('Alice', 10, 30.5),
    ('Bob', 12, 35.3),
    ('Charlie', 11, 32.1)
]
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

# レコード配列の作成
rec_array = np.array(data, dtype=dtype).view(np.recarray)

# フィールドへのアクセス（フィールド名）
print(rec_array['name'])   # ['Alice' 'Bob' 'Charlie']
print(rec_array['age'])    # [10 12 11]
print(rec_array['weight']) # [30.5 35.3 32.1]

# フィールドへのアクセス（属性アクセス）
print(rec_array.name)   # ['Alice' 'Bob' 'Charlie']
print(rec_array.age)    # [10 12 11]
print(rec_array.weight) # [30.5 35.3 32.1]


['Alice' 'Bob' 'Charlie']
[10 12 11]
[30.5 35.3 32.1]
['Alice' 'Bob' 'Charlie']
[10 12 11]
[30.5 35.3 32.1]
